language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  slack: workspace:token
  email:
    recipients:
      - gregoesme@gmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: b21b45ce-5242-4e5e-acf5-e6dfeed56a5c
  app: platzi-store-backend
  on:
    repo: jgestradam/platzi-store-backend